version: 2

sources:
  - name: staging
    database: terraform-demo-448809
    schema: week_4
      # loaded_at_field: record_loaded_at
    tables:
      - name: green_taxi
      - name: yellow_taxi
         # freshness:
           # error_after: {count: 6, period: hour}
